
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
spec:
  containers:
  - name: test
    image: busybox
    command: [ "/bin/bash"]
    args: ["c", "sleep 3600" ]
    volumeMounts:
    - name: workdir
      mountPath: "/data0"
      name: pvol0
  volumes:
    - name: pvol0
      persistentVolumeClaim:
        claimName: pvol0
